---
name: Build

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Windows
        uses: microsoft/setup-msbuild@v1
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Create build directory
        shell: bash
        run: mkdir build

      - name: Setup CMake
        shell: bash
        working-directory: build
        run: |
          export UseMultiToolTask=true
          cmake ..

      - name: Build
        shell: bash
        working-directory: build
        run: |
          export UseMultiToolTask=true
          cmake --build . --config Release

      - name: Run UNIX
        if: ${{ matrix.os != 'windows-latest' }}
        shell: bash
        working-directory: build
        run: |
          cmake --build . --target run

      - name: Run Windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: bash
        working-directory: build
        run: |
          ./Release/CPUCount.exe
